version: '3.9'

services:
  his_api:
    build: .
    container_name: hotel_information_system_api
    deploy:
      resources:
        limits:
          cpus: "0.5" # 0.5 cores
          memory: 512M # 512 MB of RAM
    restart: unless-stopped
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: hotel_db
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - server_network

networks:
  server_network:
    external: true # tell docker to use existing network named "tunnel"
