name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install dependencies
      run: composer install

    - name: Run passport:install
      run: php artisan passport:install

    - name: Deploy to Vercel
      run: vercel --prod
      env:
        VERCEL_TOKEN: AI93rMODRR0hCRVwk2xvSFEt
